### PR TITLE
Rewrite to JAX-RS Jersey 2.+ implementation with Jackson Json provider

### PR DESCRIPTION
**Pull request by konikvranik**
Hi,

due to inability to use jersey 1.+ on Android I upgraded JToggl to Jersey 2.+ which is JAX-RS compliat.
So i offer to you to merge my changes to your original code which is referenced from toggl api page.

Best regards

Petr

### CODE REVIEW

**Comment by bbaumgartner** [comment]
Thank you very much Petr. This looks great but is a huge change. What was the motivation to move classes to the new package .domain?

**Comment by konikvranik** [comment]
I prefer to have separated POJO beans and execution doce. So POJOs are moved into "domain" package and execution code left in library root.

**Comment by konikvranik** [comment]
@bbaumgartner Hi, do you want to integrate this PR or should I close it.

**Comment by bbaumgartner** [comment]
Hi @konikvranik 

I'm terrible sorry, but I didn't have time and probably wont have time in the future. I suggest to close this and redirect people to your fork.

Regards
Benno

**Pull request closed without merging**
